# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 358054e5aad500fb8dff11644ee8466e31ec8bac2e900e518990f49fd4b3565e3c9dcecf5d478bd57c7541aae1d255e96b14af7ef8879f1ff48b003353d41dea

test:
  secret_key_base: 327a8e819d04dd1e15b7a72542268f85f1035e943d88cf729ce900d26e1145a2a178cfcac478e7d5555a44828195eca0478574a143953f4aa5f5e8f53b833c46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
